import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
import Apollo from "../app/lib/apollo";
import Image from "next/image";
export const metadata: Metadata = {
  title: "習慣養成工具",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Apollo>
        <body className={inter.className}>
          {/* <div className="navbar  bg-primary-focus">
            <div className="flex-1">
              <img src="https://github.com/chunjull/Habit-Piggy/blob/main/assets/images/icon.png?raw=true" />
              <span className="font-sans hover:font-serif">Habit Piggy</span>
            </div>
            <div className="flex-none">
              <ul className="menu menu-horizontal px-1">
                <li>
                  <a href="/login">登入</a>
                </li>
                <li>
                  <details>
                    <summary>Parent</summary>
                    <ul className="p-2 bg-base-100">
                      <li>
                        <a href="/about">Link 1</a>
                      </li>
                      <li>
                        <a href="/products">Link 2</a>
                      </li>
                    </ul>
                  </details>
                </li>
              </ul>
            </div>
          </div> */}

          <header className="header  bg-primary-content text-white flex">
            <ul className=" flex justify-around w-full ">
              <li className=" flex  items-center py-2 ">
                <Image
                  width={40}
                  height={40}
                  src="https://github.com/chunjull/Habit-Piggy/blob/main/assets/images/icon.png?raw=true"
                  alt=""
                />
                <span className="font-sans hover:font-serif">
                  {" "}
                  <a href="/">Habit Piggy</a>{" "}
                </span>
              </li>
              <ul className=" flex items-center gap-5">
                <li>
                  {" "}
                  <a href="/article">推薦文章</a>{" "}
                </li>
                <li>
                  {" "}
                  <a href="/subscription">訂閱方案</a>{" "}
                </li>
                <li>
                  {" "}
                  <a href="/login">會員登入</a>{" "}
                </li>
              </ul>
            </ul>
          </header>

          <div className="content bg-white ">{children}</div>

          <footer className="footer p-10 bg-primary-content text-white ">
            <ul className="  lg:flex justify-around w-full ">
              <li className=" flex  items-center ">
                <Image
                  width={40}
                  height={40}
                  src="https://github.com/chunjull/Habit-Piggy/blob/main/assets/images/icon.png?raw=true"
                  alt=""
                />
                <span className="font-sans hover:font-serif lg:text-xl sm:text-3xl">
                  Habit Piggy
                </span>
              </li>
              <li>© 2023. All Rights Reserved.</li>
            </ul>
          </footer>
        </body>
      </Apollo>
    </html>
  );
}
